### ISSUE TITLE
Side note about order.roa for readme

### ISSUE THREAD

**Issue by All-Chronical** [CL-9a/RoAOrderSorter#10]
order.roa and categories.roa files will only exist/be generated if the order of the workshop characters have already been tampered with/modified on the device in the extras>workshop section of the game. Now I know people seeking this tool probably already have the file generated, but I thought it's worth a mention.

**Comment by CL-9a** [comment]
Thanks for the note, added and ordered the README a bit!

Just for the record, feel free to propose wording changes directly on Github! (eg. I think this link should run you through the whole forking-and-pull-requesting workflow: https://github.com/CL-9a/RoAOrderSorter/edit/main/README.md)
