### ISSUE TITLE
Unable to load order.roa

### ISSUE THREAD

**Issue by All-Chronical** [CL-9a/RoAOrderSorter#9]
Tested on both Chromium and Edge. Upon tying to pick order.roa from `C:\Users\user\AppData\Local\RivalsofAether\workshop` (also had to go out of my way to find the location. A little hint in readme would have been useful ¯\_(ツ)_/¯), I get the message from my browser:
![image](https://github.com/user-attachments/assets/d85f73d5-37a1-445b-af68-1b9c2d7e0385)

Fine, copy over the file to desktop and try to upload it from there. Still upon upload both via drag and drop and manual file selection, nothing happens. Go to inspect element, there's an error:

![image](https://github.com/user-attachments/assets/f79ef726-e256-49bb-83bd-36b5934a5cd1)

awesome tool! please help<3

**Comment by CL-9a** [comment]
Hi! You're right I forgot to even mention where the file would be, added to the readme! (eventually I'll add it to the tool itself)
And damn that's annoying that this folder can't be opened directly, had no idea

Good thinking checking the console! I should add error alerts when things break here. I just fixed an edge case so maybe with a little luck it's fixed, can you try again?  I also added more logs that should make it easier to debug, so if still breaks could you screenshot the console again too?
Thanks!

**Comment by All-Chronical** [comment]
> Hi! You're right I forgot to even mention where the file would be, added to the readme! (eventually I'll add it to the tool itself) And damn that's annoying that this folder can't be opened directly, had no idea
> 
> Good thinking checking the console! I should add error alerts when things break here. I just fixed an edge case so maybe with a little luck it's fixed, can you try again? I also added more logs that should make it easier to debug, so if still breaks could you screenshot the console again too? Thanks!

Yup whatever you cooked fixed it. I appreciate it! 🙌
